<?php
	include_once 'header.php';
?>

<style>
	<?php include 'CSS\historia.css'?>
	<?php include 'CSS\virtavesiekosysteemi.css'?>
</style>

		<div class="main">
			<div class="teksti">
				<h1>VIRTAVESIKUNNOSTUKSEN HISTORIA</h1>
				<h2>Taustaa</h2>
				<p>Useat ympäristömuutokset ovat selvästi heikentäneet kalakantojen tilaa ja kalastusmahdollisuuksia Suomessa. Ihmistoiminnasta johtuvia muutoksia, kuten vesistörakentamisen ja jätevesien aiheuttamia muutoksia on pyritty kompensoimaan pääasiassa kalanistutuksin ja rahallisesti korvaamalla. Toimenpiteet, joissa pyrkimyksenä on kokonaisvaltainen kalavesien ja kalakantojen tilan parantaminen, ovat melko uusia ja kehittyviä kalavesien hoitomuotoja.<img src="IMG/Halistenpato.jpg" class="center"></p>
				<p>Vesistöjen luontaista hydrologiaa (veden kiertokulku) ovat muuttaneet padot ja säännöstelyt. Esimerkiksi suurin osa Suomen suurimmista joista ovat säännösteltyjä ja edelleen merkittävä osa luonnonjärviemme pinta-alasta on säännösteltyä. Iso osa säännöstelystä tehdään palvelemaan sähköntuotantoa, veden hankintaa ja tulvasuojelua. Kalojen elinolosuhteisiin ovat vaikuttaneet näkyvimmin säännöstelystä johtuvat vedenpinnan korkeusmuutokset. Suurimman laskun jokien patoamisesta ovat maksaneet vaelluskalakannat.</p>
				<img src="IMG/uitto.jpg" class="center" style="width: 40%"><p>Säännöstelyn piirissä on paljon sellaisia koskia, joista löytyy vähäisiä uittorakenteita. Lisäksi vesistöjemme ja niiden valuma-alueiden vedenpidätyskykyä on muutettu merkittävästi. Perattuja koskia maastamme löytyy kymmeniä tuhansia kilometrejä, mutta luonnontilaisia jokia ja puroja on maassamme vain murto-osa. Suurin osa maamme joista ja puroista on aikojen saatossa perattu ja niiden valuma-alueista ojitettu uiton, tulvasuojelun ja kuivatuksen nimissä. Näin toimimalla on samalla hävitetty kalojen ja rapujen kutu-, poikastuotanto- ja oleskelualueita sekä nopeutettu virtaamavaihteluita.</p><br>
				<p>Lisäksi purojen ja jokien varsia reunustavaa puustoa ja kasvillisuutta on raivattu suuressa mittakaavassa pois viljelymaiden tieltä. Raivaaminen on johtanut kiintoaine- ja ravinnekuormituksiin, vienyt suojapaikkoja ja ravinnonlähteitä vesieläimiltä sekä lisännyt vesikasvillisuutta ja nostanut vesistöjen lämpötilaa.</p><br>
				<p>Vesistöjen kalataloudellinen kunnostaminen on käynnistynyt uhanalaisten, kiireellistä elvyttämistä vaativien lohikalakantojen lisääntymisalueilla. Jäljellä olevista lohikalakannoista vain pieni osa on alkuperäisiä ja niistäkin monet ovat kuolemassa sukupuuttoon. (Kalataloudellisten kunnostusten kehittämistyöryhmän raportti 2004)</p><br>
				<h2>Koskien ja muiden virtavesien kunnostukset</h2>
				<p>Nykymuotoisia kalataloudellisia koskikunnostuksia alettiin tekemään yksittäisinä hankkeina 1970-luvun loppupuolella eri puolilla maata. Laukaisevana tekijänä kunnostustoiminnan aloittamiselle oli huolestuneisuus vaelluskalojen heikosta luontaisesta lisääntymisestä. Elinkiertonsa luonnossa säilyttäneiden ja voimalaitosrakentamiselta välttyneiden vaelluskalalajien kannat heikkenivät siinä määrin 1980-luvulla, että kalanpoikasten viljelyyn tarvittavien emokalastojen uusiminen alkoi vaikeutua. Tarve kunnostuksille oli suuri, koska melkein kaikki virtavedet oli perattu uiton, kuivatuksen, tulvasuojelun, voimatalouden tai muiden syiden takia.</p>
				<img src="IMG/huopana.jpg" class="center" ><p>Virtavesien kunnostustoiminta lisääntyi siirryttäessä 1980-luvulle ja tällöin aloitettiin lisäksi nykyaikaisten kalateiden rakentaminen. Maa- ja metsätalousministeriöön tuli 1980-luvulla paljon aloitteita kalataloudellisista kunnostuksista. Hidasteita kunnostustoiminnan käynnistämiselle aiheuttivat muun muassa erillisenrahoituksen puuttuminen, tiedon puute ja vanhojen velvoitteiden toimeenpanoon liittyvät oikeudelliset kysymykset.</p><br>
				<p>Vuonna 1982 Vesirakentamistöiden tarvetoimikunta esitti mietinnössään koko maan kattavan kalakantojen elvyttämisohjelman laatimista kalataloudellista kunnostuksista ja kalateistä. Vuonna 1985 julkaistu Vaelluskalakantojen elvyttämistyöryhmän mietintö on ensimmäinen valtakunnallinen kalataloudellisten kunnostusten toimenpideohjelma, johon sisältyivät pitkän ja lyhyen aikavälin kunnostusohjelma, kunnostusten periaatteet ja kohteet. Sen tavoitteena oli turvata jäljellä olevien vaelluskalakantojen säilyminen geneettisesti monimuotoisina luontaisen lisääntymisen kautta sekä turvata viljely luonnosta hankitun mädin avulla. Suurimmaksi vaelluskalakantojen lisääntymistä heikentäväksi tekijäksi nähtiin elinympäristön huono tila. Vesirakentamisen haitoista määrätyt kalatalousvelvoitteet olivat pääosin istutusvelvoitteita.</p><br>
				<p>Vuonna 1982 Keski-Suomessa tehtiin oma kattava kalataloudellinen kunnostusohjelma; VIRVE-raportti. Virtavesien kalataloudellisesta kunnostustarpeesta tehtiin 1980-luvulla useampia muita maakuntakohtaisia selvityksiä, esimerkiksi koskikalastojen inventointeja, joista julkaistuissa raporteissa tuotiin esille kalataloudellisia kunnostuskohteita ja annettiin peräti yksityiskohtaisia ohjeita kunnostusten toteuttamisesta.</p>
				<img src="IMG/salmon.jpg" class="center" style="width: 60%;"><p>1980-luvun alkupuolella kalatalousviranomaisten toimeksiannosta kalataloudellisia kunnostuksia alettiin toteuttamaan. Aluksi kalataloudellisia kunnostushankkeita rahoitettiin esimerkiksi työllisyysvaroin sekä vuodesta 1984 lähtien valtion tulo- ja menoarvion kalataloudelliset kunnostus- ja rakennushankkeet -momentilta. Jokien kalataloudellinen tila saattoi heikentyä, kun valtiolle vesilain mukaisina velvoitteina kuuluvia uittosääntöjen kumoamistöitä ehdittiin toteuttaa runsaasti poistamalla vesistöistä ainoastaan haitalliset uittolaitteet, kuten säästöpadot ja puusuisteet.</p><br>
				<p>Korkeimman hallinto-oikeuden vuonna 1977 tekemän päätöksen jälkeen myös koskien perkaus katsottiin vesistön käytölle haittaa aiheuttavaksi uittolaitteeksi, haitaten mm. kalojen vaellusta. Vastedes uittosäännön kumoamispäätökset pitivät sisällään kalojen elinolojen parantamisen katsottaessa sen olevan tarpeellista. Vuonna 1986 korkeimmalta hallinto-oikeudelta tuli päätös, jossa vesihallitus määrättiin kiveämisen lisäksi tekemään kutusoraikkoja. Uittosääntöihin liittyviä koskien entisöintejä voitiin pitää kalataloudellisiin kunnostuksiin verrattavina kyseisen päätöksen jälkeen.</p><br>
				<p>Alkuaikoina kunnostusmenetelmistä oli vain vähän tietoa. Kunnostusten suunnittelussa ja toteutuksessa sovellettiin muualta Euroopasta ja Pohjois-Amerikasta saatua tutkimustietoa lohikalojen elinympäristövaatimuksista. Joitakin tutkimuksia tehtiin myös Suomessa 1980-luvulla kutupaikkojen ominaisuuksista sekä eri-ikäisten poikasten elinympäristöistä.</p><br>
				<p>Alkuvaiheessa kunnostusmenetelmät kehittyivät useita kunnostusmalleja kokeilemalla ja seuraamalla kunnostuksen vaikutuksia etupäässä sähkökoekalastuksin ja istutuskokein. Puroja on kunnostettu pienimuotoisesti jo kymmeniä vuosia talkoo- ja viranomaistyönä. Nykyisin niitä rahoitetaan useiden eri tahojen kautta. EU on yksi merkittävin rahoittaja. (Kalataloudellisten kunnostusten kehittämistyöryhmän raportti 2004)</p><br>
			</div>
		</div>
	</div>

<?php
	include_once 'footer.php';
?>